[package]
name = "packet_forwarder"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet = "0.34"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.47", features = ["derive"] }
